# Site settings
title: 空谷闲谈录
email: ysu.th@dartmouth.edu
description: > # this means to ignore newlines until "baseurl:"
    记录我在达特茅斯的所学所想
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.yuchensu.com" # the base hostname & protocol for your site
twitter_username: psaux0
github_username: psaux0

# Build settings
markdown: kramdown
